name: Lint and Format

on:
  push:
    branches: [main, staging]
  pull_request:
    branches: [main, staging]

jobs:
  lint-and-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: |
          npm run lint
        continue-on-error: false
        id: eslint

      - name: Run Prettier check
        run: |
          npm run format:check
        continue-on-error: false
        id: prettier

      - name: Annotate ESLint issues
        if: failure() && steps.eslint.outcome == 'failure'
        run: |
          echo "::error::ESLint found issues in your code. Run 'npm run lint:fix' to automatically fix some issues."
          npm run lint || true

      - name: Annotate Prettier issues
        if: failure() && steps.prettier.outcome == 'failure'
        run: |
          echo "::error::Prettier found formatting issues in your code. Run 'npm run format' to automatically fix formatting."
          npm run format:check || true

      - name: Provide fix suggestions
        if: failure()
        run: |
          echo "::notice title=Fix Suggestions::To fix linting issues, run: npm run lint:fix"
          echo "::notice title=Fix Suggestions::To fix formatting issues, run: npm run format"
          echo "::notice title=Fix Suggestions::After fixing issues, commit the changes and push again."
